apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: q0rr7rwaj-go 
  janus-idp.io/tekton: q0rr7rwaj-go
  backstage.io/kubernetes-id: q0rr7rwaj-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q0rr7rwaj-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml